on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      docker-url:
        required: true
        type: string
      docker-repo:
        required: true
        type: string
    secrets: 
      GCP_SA_KEY:
        required: true

  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ inputs.docker-url }}/${{ inputs.docker-repo }}
    steps:
    - uses: actions/checkout@v3

    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v3
      with:
        name: docker-image
        path: .artifacts

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker-url  }}
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Load the Docker image
      run: docker load < .artifacts/image.tgz

    - name: Load the Docker image
      run: docker tag image:latest ${{ env.DOCKER_IMAGE }}:${{ inputs.version }}

    - name: Publish Docker Image
      run: docker push ${{ env.DOCKER_IMAGE }}:${{ inputs.version }}
