name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish-staging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: pkg.dev
        username: _json_key_base64
        password: ${{ secrets.STG_GCP_TOKEN }}
        
    - id: version
      name: Generate Version
      run: echo "version=$(TZ=':America/Chicago' date +'Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag us-central1-docker.pkg.dev/stg-main-377820/tst/core:${{ steps.version.outputs.version}}

    - name: Debug
      run: cat ~/.docker/config.json

    - name: Publish Docker Image
      run: docker push us-central1-docker.pkg.dev/stg-main-377820/tst/core:${{ steps.version.outputs.version}}
