name: Full Deploy

on:
  push:
    branches: ["main", "stg"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

    - uses: actions/checkout@v3
    - id: version
      name: Generate version
      run: echo "version=$(TZ=':America/Chicago' date +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image
      run: |
        mkdir .artifacts
        docker build . --file Dockerfile --tag image:latest
        docker save image:latest > .artifacts/image.tgz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: .artifacts
        retention-days: 1

  staging:
    environment: staging
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit
    with:
      version: ${{ needs.build.outputs.version }}
      docker-url: ${{ vars.DOCKER_URL }}
      docker-repo: ${{ vars.DOCKER_REPO }}

  production:
    environment: production
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit
    with:
      version: ${{ needs.build.outputs.version }}
      docker-url: ${{ vars.DOCKER_URL }}
      docker-repo: ${{ vars.DOCKER_REPO }}
