name: test:w

on:
  push:
    branches: ["main", "stg"]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.make-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ github.repository.name }}
    - run: echo ${{ github.event.repository.name }}
