name: Full Deploy

on:
  push:
    branches: ["main", "stg"]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.make-tag.outputs.tag }}
    steps:

    - uses: actions/checkout@v3
    - id: make-tag
      name: Generate version
      run: echo "tag=$(TZ=':America/Chicago' date +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image
      run: |
        mkdir .artifacts
        docker build . --file Dockerfile --tag image:latest
        docker save image:latest > .artifacts/image.tgz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: .artifacts
        retention-days: 1

  staging:
    uses: ./.github/workflows/docker-publish.yaml
    needs: build
    with:
      environment: staging
      tag: ${{ needs.build.outputs.tag }}
      docker-url: ${{ vars.DOCKER_URL }}
      docker-repo: ${{ vars.DOCKER_REPO }}
    secrets: 
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  production:
    uses: ./.github/workflows/docker-publish.yaml
    needs: ["build", "staging"]
    with:
      environment: production
      tag: ${{ needs.build.outputs.tag }}
      docker-url: ${{ vars.DOCKER_URL }}
      docker-repo: ${{ vars.DOCKER_REPO }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
